# Generated by Django 4.2.9 on 2024-01-20 02:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retriever", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("email", models.CharField(max_length=255)),
                ("creds", models.JSONField(blank=True, null=True)),
                ("token", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="copy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="history_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="internal_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="label_ids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="recipient",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="sender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="snippet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="thread_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="email_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_messages",
                to="retriever.emailaccount",
            ),
        ),
    ]
