# Generated by Django 4.2.9 on 2024-01-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retriever", "0002_emailaccount_emailmessage_body_emailmessage_copy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="service_type",
            field=models.CharField(blank=True, choices=[("gmail", "Gmail")], max_length=255, null=True),
        ),
    ]
