# Generated by Django 4.2.9 on 2024-01-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retriever", "0003_emailaccount_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="email",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="service_type",
            field=models.CharField(blank=True, choices=[("gmail", "Gmail")], max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="external_id",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="history_id",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="internal_date",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="recipient",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="sender",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="thread_id",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
