# Generated by Django 4.2.9 on 2024-01-31 02:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retriever", "0004_alter_emailaccount_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("name", models.CharField(blank=True, max_length=5000, null=True)),
                ("email", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "email_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_message_senders",
                        to="retriever.emailaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="email_sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_messages",
                to="retriever.emailmessagesender",
            ),
        ),
    ]
